export function getMarkdownEditorOptions(t) {
  return {
    spellChecker: false,
    status: false,
    lineWrapping: true,
    toolbar: [
      "bold",
      "italic",
      "strikethrough",
      "|",
      "heading-1",
      "heading-2",
      "heading-3",
      "|",
      "code",
      "quote",
      "table",
      "horizontal-rule",
      "|",
      "unordered-list",
      "ordered-list",
      "|",
      "link",
      "image",
      "|",
      "preview",
      "side-by-side",
      "fullscreen",
      "|",
      "guide",
    ],
    placeholder: t("editor.placeholder"),
  };
}
